/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SENSOR_PB_H_INCLUDED
#define PB_SENSOR_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _BKITSensorData {
    uint32_t sensor_id;
    uint32_t light;
    uint32_t potentiometer;
    float voltage;
    float current;
    float temperature;
    uint64_t timestamp;
} BKITSensorData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define BKITSensorData_init_default              {0, 0, 0, 0, 0, 0, 0}
#define BKITSensorData_init_zero                 {0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define BKITSensorData_sensor_id_tag             1
#define BKITSensorData_light_tag                 2
#define BKITSensorData_potentiometer_tag         3
#define BKITSensorData_voltage_tag               4
#define BKITSensorData_current_tag               5
#define BKITSensorData_temperature_tag           6
#define BKITSensorData_timestamp_tag             7

/* Struct field encoding specification for nanopb */
#define BKITSensorData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sensor_id,         1) \
X(a, STATIC,   SINGULAR, UINT32,   light,             2) \
X(a, STATIC,   SINGULAR, UINT32,   potentiometer,     3) \
X(a, STATIC,   SINGULAR, FLOAT,    voltage,           4) \
X(a, STATIC,   SINGULAR, FLOAT,    current,           5) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,       6) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         7)
#define BKITSensorData_CALLBACK NULL
#define BKITSensorData_DEFAULT NULL

extern const pb_msgdesc_t BKITSensorData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define BKITSensorData_fields &BKITSensorData_msg

/* Maximum encoded size of messages (where known) */
#define BKITSensorData_size                      44
#define SENSOR_PB_H_MAX_SIZE                     BKITSensorData_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
